name: MagicShell
version: 1.1
description: Experience the wisdom of the Magic Shell!
author: Taermi
main: com.github.taermi.Main
api-version: '26.1'
website: https://github.com/Taermi
commands:
  ms:
    aliases: magicshell
    permission: ms.allow
